## task-1

### t1.py

In [1]:
import numpy as np

n1=np.arange(5,51,5)
print(n1)
print(n1.shape)
print(n1.dtype)

[ 5 10 15 20 25 30 35 40 45 50]
(10,)
int64


### t2.py

In [2]:
import numpy as np

n1=np.zeros([4,4],dtype=int)
print(n1)

for i in range(4):
    n1[i][i]=1
    
print(n1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### t3.py

In [3]:
import numpy as np

n1=np.linspace(0,2*np.pi,20)
print(n1)

n2=np.sin(n1)
print(n2)

[0.         0.33069396 0.66138793 0.99208189 1.32277585 1.65346982
 1.98416378 2.31485774 2.64555171 2.97624567 3.30693964 3.6376336
 3.96832756 4.29902153 4.62971549 4.96040945 5.29110342 5.62179738
 5.95249134 6.28318531]
[ 0.00000000e+00  3.24699469e-01  6.14212713e-01  8.37166478e-01
  9.69400266e-01  9.96584493e-01  9.15773327e-01  7.35723911e-01
  4.75947393e-01  1.64594590e-01 -1.64594590e-01 -4.75947393e-01
 -7.35723911e-01 -9.15773327e-01 -9.96584493e-01 -9.69400266e-01
 -8.37166478e-01 -6.14212713e-01 -3.24699469e-01 -2.44929360e-16]


### t4.py

In [4]:
import numpy as np

n1=np.random.randint(10,99,(3,3))
print(n1)

print(np.max(n1))
print(np.min(n1))

[[81 80 70]
 [21 37 94]
 [68 47 75]]
94
21


### t5.py

In [5]:
import numpy as np

n1=np.zeros([5,5],dtype=int)

n1[::2,::2]=1
n1[1::2,1::2]=1

print(n1)



[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


## task-2

### t1.py

In [6]:
import numpy as np

n1=np.ones([4,3,2])
print(n1)


print(f"Dimension:{n1.ndim}")
print(f"Shape:{n1.shape}")
print(f"Size:{n1.size}")
print(f"Bytes of 1 Element:{n1.itemsize}")
print(f"Total Bytes:{n1.nbytes}")

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
Dimension:3
Shape:(4, 3, 2)
Size:24
Bytes of 1 Element:8
Total Bytes:192


### t2.py

In [7]:
import numpy as np

n=np.array([1,2,3,4,5],dtype=np.int64)
n1=np.arange(60,100,10,dtype=np.int64)
print(n1.dtype)
print(n1.nbytes)

n2=n1.astype(np.float32)
print(n2.dtype)
print(n2.nbytes)

int64
32
float32
16


### t3.py

In [8]:
import numpy as np

def describe(n1):
    
    print(f"Shape:{n1.shape}")
    print(f"Size:{n1.size}")
    print(f"Dimension:{n1.ndim}")
    print(f"Data Type:{n1.dtype}")
    print(f"One Element Bytes:{n1.itemsize}")
    print(f"Total Bytes:{n1.nbytes}")
    
n1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
describe(n1)

Shape:(2, 2, 2)
Size:8
Dimension:3
Data Type:int64
One Element Bytes:8
Total Bytes:64


## task-3

### t1.py

In [9]:
import numpy as np

arr = np.arange(1, 26).reshape(5, 5)
print(arr)

newarr=arr[1:4,1:4]
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


### t2.py

In [10]:
import numpy as np

n1=np.random.randint(0,50,(4,4))

print(n1)
n2=n1[::-1]

print(n2)

[[34  6 20  5]
 [19 21 47 19]
 [27 49  3 10]
 [29 17 26  2]]
[[29 17 26  2]
 [27 49  3 10]
 [19 21 47 19]
 [34  6 20  5]]


### t3.py

In [11]:
import numpy as np

n1=np.array([[34, -5, 12, 0, -8, 99, 47, -1]])

n2=n1[n1<0]

n1[n1<0]=np.abs(n1[n1<0])

print(f"Negative Items:{n2}")
print(f"New Array:{n1}")

Negative Items:[-5 -8 -1]
New Array:[[34  5 12  0  8 99 47  1]]


### t4.py

In [12]:
import numpy as np

n1=np.eye(6,6)

print(n1)
n1[1:4,1:4]=5

print(n1)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 5. 5. 5. 0. 0.]
 [0. 5. 5. 5. 0. 0.]
 [0. 5. 5. 5. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### t5.py

In [13]:
import numpy as np

n1=np.random.randint(0,101,(10))

grade=np.where(n1>=80,'A',
               np.where(n1>=60,'B','C'))
print(n1)
print(grade)

[61  8 29  0 21 16 47 16 12  8]
['B' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C']


## task-4

### t1.py

In [14]:
import numpy as np

n1=np.random.randint(1,20,(3,3))
n2=np.random.randint(1,5,(3,3))


print(f"n1:\n{n1}")
print(f"n2:\n{n2}")
print(f"\nProduct:\n{n1*n2}")
print(f"Division:\n{n1//n2}")
print(f"Power n1 raised to n2:\n{n1**n2}")

n1:
[[17 10 15]
 [ 7 19  9]
 [ 1 14 13]]
n2:
[[1 3 3]
 [2 2 2]
 [3 1 2]]

Product:
[[17 30 45]
 [14 38 18]
 [ 3 14 26]]
Division:
[[17  3  5]
 [ 3  9  4]
 [ 0 14  6]]
Power n1 raised to n2:
[[  17 1000 3375]
 [  49  361   81]
 [   1   14  169]]


### t2.py

In [15]:
import numpy as np

n1=np.random.randint(0,50,10)

normalised=(n1-n1.mean())/n1.std()

print(f"Original Array:{n1}")
print(f"Normalised Array:{normalised}")

print(f"Mean:{normalised.mean()} Standard Deviation:{normalised.std()}")

Original Array:[39 46 18 38  1 43  6 47 37 48]
Normalised Array:[ 0.40475442  0.82763217 -0.86387883  0.34434331 -1.89086765  0.64639884
 -1.58881211  0.88804327  0.2839322   0.94845438]
Mean:1.887379141862766e-16 Standard Deviation:1.0


### t3.py

In [16]:
import numpy as np

n1=np.random.randint(0,50,(4,5))

print(f"Matrix:{n1}")
print(f"Overall Sum:{n1.sum()}")
print(f"Row Wise Sum:{n1.sum(axis=1)}")
print(f"Column Wise Sum:{n1.sum(axis=0)}")
print(f"Column Wise Mean:{n1.mean(axis=0)}")

min_index = np.unravel_index(n1.argmin(), n1.shape)
print(f"Index of Minimum:{min_index}")

Matrix:[[46  3 25 44 43]
 [48  9 37 42 24]
 [22 43  1 20  5]
 [11 26 26 12 16]]
Overall Sum:503
Row Wise Sum:[161 160  91  91]
Column Wise Sum:[127  81  89 118  88]
Column Wise Mean:[31.75 20.25 22.25 29.5  22.  ]
Index of Minimum:(np.int64(2), np.int64(2))


### t4.py

In [17]:
import numpy as np

n = np.arange(1, 10)

table = n[:, np.newaxis] * n

print(f"9x9 Multiplication Table:\n{table}")


9x9 Multiplication Table:
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


### t5.py

In [18]:
import numpy as  np
n1=np.linspace(0, 2 * np.pi, 100)

sinV=np.sin(n1)
cosV=np.cos(n1)


ans=sinV**2 + cosV**2

print(f"sin^2(x) + cos^2(x):\n{ans}")

print(f"\nAll values close to 1?:{np.allclose(ans, 1)}")


sin^2(x) + cos^2(x):
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]

All values close to 1?:True


## task-5

### t1.py

In [19]:
import numpy as np

n1=np.arange(1,31)

a=n1.reshape((5,6))

b=n1.reshape((2,3,5))

c=n1.reshape((6,5))

print(f"Original Array:\n{n1}")
print(f"Shape(5,6):\n{a}")
print(f"Shape(2,3,5):\n{b}")
print(f"Shape(6,5):\n{c}")

print(f"Size of Shape(5,6):{a.size}")
print(f"Size of Shape(2,3,5):{b.size}")
print(f"Size of Shape(6,5):{c.size}")

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
Shape(5,6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Shape(2,3,5):
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
Shape(6,5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
Size of Shape(5,6):30
Size of Shape(2,3,5):30
Size of Shape(6,5):30


### t2.py

In [20]:
import numpy as np

n1=np.random.randint(1, 10, (3, 4))
n2=np.random.randint(1, 10, (3, 4))

print(f"Array n1:\n{n1}")
print(f"\nArray B:\n{n2}")

Vstack = np.vstack((n1, n2))
Hstack = np.hstack((n1, n2))

print(f"\nVertical Stack:\n{Vstack}")
print(f"Shape:{Vstack.shape}")

print(f"\nHorizontal Stack:\n{Hstack}")
print(f"Shape:{Hstack.shape}")

Array n1:
[[2 7 7 4]
 [4 1 1 2]
 [1 4 6 8]]

Array B:
[[6 3 5 7]
 [9 3 9 4]
 [1 7 6 9]]

Vertical Stack:
[[2 7 7 4]
 [4 1 1 2]
 [1 4 6 8]
 [6 3 5 7]
 [9 3 9 4]
 [1 7 6 9]]
Shape:(6, 4)

Horizontal Stack:
[[2 7 7 4 6 3 5 7]
 [4 1 1 2 9 3 9 4]
 [1 4 6 8 1 7 6 9]]
Shape:(3, 8)


### t3.py

In [21]:
import numpy as np

n1=np.array([10,20,30,40])

column=n1[:,np.newaxis]
print(f"Column Vector:{column}")

n2=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print(f"\nAddition:\n{column+n2}")

Column Vector:[[10]
 [20]
 [30]
 [40]]

Addition:
[[11 12 13]
 [24 25 26]
 [37 38 39]
 [50 51 52]]


### t4.py

In [22]:
import numpy as np

n1=np.arange(1, 25).reshape(6,4)

print("Original Array:")
print(n1)

pieces = np.split(n1, 3, axis=0)

for i, part in enumerate(pieces, start=1):
    print(f"\nPiece {i}:")
    print(part)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Piece 1:
[[1 2 3 4]
 [5 6 7 8]]

Piece 2:
[[ 9 10 11 12]
 [13 14 15 16]]

Piece 3:
[[17 18 19 20]
 [21 22 23 24]]


## main-task

### t1.py

In [23]:
import numpy as np

n=np.array([
    [72,85,60,78],
    [88,92,95,90],
    [45,52,48,55],
    [65,70,72,68]
])

total_student=n.sum(axis=1)
avg_student=n.mean(axis=1)

print(f"Total Marks per Student:{total_student}")
print(f"Average Marks per Student:{avg_student}")

avg_subject=n.mean(axis=0)
print(f"Average Marks per Subject:{avg_subject}")

classification=np.where(avg_student>=80,"Distinction",
                        np.where(avg_student>=65,"Merit",
                                 np.where(avg_student>=50,"Pass","Fail")))

print(f"\nClassification:\n{classification}")

Total Marks per Student:[295 365 200 275]
Average Marks per Student:[73.75 91.25 50.   68.75]
Average Marks per Subject:[67.5  74.75 68.75 72.75]

Classification:
['Merit' 'Distinction' 'Pass' 'Merit']


### t2.py

In [24]:
import numpy as np

sales = np.random.randint(100, 1000, (12, 4))

print("Sales Data:\n", sales)

month_total = np.sum(sales, axis=1)
best_month = np.argmax(month_total) + 1

print("\nBest Selling Month:", best_month)

product_total = np.sum(sales, axis=0)
worst_product = np.argmin(product_total) + 1

print("Worst Product:", worst_product)

good_months = np.where(np.all(sales > 500, axis=1))[0] + 1

print("Months where all products sold more than 500 units:")
print(good_months)

Sales Data:
 [[193 579 423 297]
 [283 656 553 331]
 [637 224 254 129]
 [993 822 595 938]
 [372 695 948 679]
 [446 363 192 802]
 [172 992 380 977]
 [558 894 566 170]
 [595 207 671 321]
 [996 629 682 160]
 [172 337 557 295]
 [406 163 417 250]]

Best Selling Month: 4
Worst Product: 4
Months where all products sold more than 500 units:
[4]


### t4.py

In [25]:
import numpy as np

def my_range(start,stop,step):
    
    n=int((stop-start)/step)
    a=np.zeros(n)
    
    for i in range(n):
        a[i]=start+i*step
        
    return a

x=my_range(2,10,2)
print(x)

[2. 4. 6. 8.]


### t5.py

In [26]:
import numpy as np

a = np.random.randint(1,100,(10,10))

print("Matrix:\n", a)

print("\nShape:", a.shape)

print("Dtype:", a.dtype)

print("Total Sum:", np.sum(a))

print("\nRow-wise Means:")
print(np.mean(a, axis=1))

print("\nColumn-wise Standard Deviations:")
print(np.std(a, axis=0))

m = np.max(a)

p = np.unravel_index(np.argmax(a), a.shape)

print("\nGlobal Max:", m)

print("Position:", p)

c = np.sum(a > 50)

print("\nCount of elements > 50:", c)

Matrix:
 [[ 4 39 21 71 11  7 38 24 53 72]
 [14 97  6 53  7 74 22 62 73 33]
 [64 69 61  1 90 44 47 16 50 33]
 [69 92 25 81 87 18 77 46 39 49]
 [ 2 67 52 98 93 24 90 30 89 69]
 [79 73 87 19 25 11 57  7 93 55]
 [44 31 76 47 28 72 75 38 12  1]
 [91 89 25 58 99 88 34 52 12 10]
 [16 52 53 70 16 89 90  4 86 87]
 [60 46  9 84 27  9 26 84 82 18]]

Shape: (10, 10)
Dtype: int32
Total Sum: 4949

Row-wise Means:
[34.  44.1 47.5 58.3 61.4 50.6 42.4 55.8 56.3 44.5]

Column-wise Standard Deviations:
[31.24435949 21.84605227 26.76658364 28.34360598 36.54326203 32.25275182
 24.61381726 24.05015592 29.06011012 27.0371966 ]

Global Max: 99
Position: (np.int64(7), np.int64(4))

Count of elements > 50: 50
