## task-1

### t1.py

In [1]:
import numpy as np

n1=np.random.randint(1,101,(6,6))

print(f"Matrix:\n{n1}")
div_by_3_5=n1[(n1%3==0)&(n1%5==0)]

print(f"Divisible by 3 and 5:{div_by_3_5}")

Matrix:
[[34 43 30 31  5 99]
 [37 26 84 95 15 61]
 [24 47 38 24 64 43]
 [66 51 71 86  2 71]
 [34 51 64 46  8 46]
 [38 42 39 44 56  3]]
Divisible by 3 and 5:[30 15]


### t2.py

In [2]:
import numpy as np

n1=np.random.randint(0,100,10)

avg=n1.mean()

replace_arr=np.where(n1>avg,1,0)

print(f"Original Array:{n1}")
print(f"Mean:{avg}")
print(f"Modified Array:{replace_arr}")

Original Array:[99 93  2 60 16 49 44 90 18 76]
Mean:54.7
Modified Array:[1 1 0 1 0 0 0 1 0 1]


### t3.py

In [3]:
import numpy as np

n1=np.random.randint(1,100,(5,5))

r=[1,3,4];c=[0,2,4]
n2=n1[np.ix_(r,c)]
print("Original Array:",n1)
print("Sub Array:",n2)

Original Array: [[89 42 29  2 56]
 [76 77 50  7  7]
 [82 55 98 46 90]
 [38 15 65 35 49]
 [77 64 32 43 34]]
Sub Array: [[76 50  7]
 [38 65 49]
 [77 32 34]]


### t4.py

In [4]:
import numpy as np

n1=np.random.randint(0,100,(4,4))

row_sort=np.sort(n1,axis=1)
col_sort=np.sort(n1,axis=0)

print(n1)
print(row_sort)
print(col_sort)

[[22 65  4 35]
 [76 90 55 10]
 [21 78 26 22]
 [56 50 72 24]]
[[ 4 22 35 65]
 [10 55 76 90]
 [21 22 26 78]
 [24 50 56 72]]
[[21 50  4 10]
 [22 65 26 22]
 [56 78 55 24]
 [76 90 72 35]]


### t5.py

In [5]:
import numpy as np

n1=np.random.randint(0,101,15)

score=[n1>=85,n1>=70,n1>=55,n1>=40]
val=['A','B','C','D']

grades=np.select(score,val,default='F')
print(n1)
print(grades)

[ 4 71 42 11 29 71 80 37 76  2 36 90 73 29 45]
['F' 'B' 'D' 'F' 'F' 'B' 'B' 'F' 'B' 'F' 'F' 'A' 'B' 'F' 'D']


## task-2

### t1.py

In [6]:
import numpy as np

n1=np.random.randint(0,100,(5,4))
print(n1)
n=np.array([1,2,3,4])
n2=np.array([10,20,30,40,50])[:,np.newaxis]
print(n1+n)
print(n1-n2)

[[65 54 85 71]
 [12 33 80 25]
 [23 41 42 64]
 [41 22 41 72]
 [80 20 83 98]]
[[ 66  56  88  75]
 [ 13  35  83  29]
 [ 24  43  45  68]
 [ 42  24  44  76]
 [ 81  22  86 102]]
[[ 55  44  75  61]
 [ -8  13  60   5]
 [ -7  11  12  34]
 [  1 -18   1  32]
 [ 30 -30  33  48]]


### t2.py

In [7]:
import numpy as np

n1=np.random.randint(0,100,(6,4))

mn=np.mean(n1,axis=0)
sd=np.std(n1,axis=0)

normalise_arr=(n1-mn)/sd

print("Original:",n1)
print("Normalise:",normalise_arr)

print("Mean:",normalise_arr.mean(),"Standard Deviation:",normalise_arr.std())

Original: [[12 59 59 46]
 [45 43 42 95]
 [93  3 91 22]
 [68 88 91 55]
 [32 28 97 13]
 [78 99 79 17]]
Normalise: [[-1.53771089  0.17083917 -0.88548497  0.16401496]
 [-0.34838762 -0.31153026 -1.74567037  1.886172  ]
 [ 1.38153712 -1.51745383  0.73368755 -0.67949053]
 [ 0.48053465  1.04513376  0.73368755  0.48032951]
 [-0.81690891 -0.7637516   1.0372824  -0.99580509]
 [ 0.84093564  1.37676275  0.12649785 -0.85522084]]
Mean: -3.700743415417188e-17 Standard Deviation: 1.0


### t3.py

In [8]:
import numpy as np

n=np.array([1,2,3,4,5])

ans=np.abs(n[:,np.newaxis]-n)
print(ans)

[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 0 1 2]
 [3 2 1 0 1]
 [4 3 2 1 0]]


## task-3

### t1.py

In [9]:
import numpy as np

m1 = np.random.randint(1, 10, (3, 3))

print("M1:\n", m1)

inverse = np.linalg.inv(m1)

print("\nInverse of M1:\n", np.round(inverse, 2))

result = np.dot(m1, inverse)

rounded_result = np.round(result, 2)

print("\nM1 * inv(M1):\n", rounded_result)

I = np.eye(3)

print(np.allclose(result, I))

M1:
 [[2 7 5]
 [5 3 6]
 [1 7 4]]

Inverse of M1:
 [[-15.    3.5  13.5]
 [ -7.    1.5   6.5]
 [ 16.   -3.5 -14.5]]

M1 * inv(M1):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
True


### t2.py

In [10]:
import numpy as np

A=np.array([[2,1],[1,3]])

B=np.array([5,10])

x=np.linalg.solve(A,B)

print("Solution:",x)

flag=np.allclose(A@x,B)
print("Verification of solution:",flag)

Solution: [1. 3.]
Verification of solution: True


### t3.py

In [11]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))

print("A:\n", A)

S = A.T @ A

print("\nSymmetric Matrix S:\n", S)

eigenvalues = np.linalg.eigvals(S)

print("\nEigenvalues:\n", np.round(eigenvalues, 2))


print(np.all(eigenvalues >= 0))

A:
 [[9 7 2]
 [8 3 9]
 [4 2 8]]

Symmetric Matrix S:
 [[161  95 122]
 [ 95  62  57]
 [122  57 149]]

Eigenvalues:
 [322.38   1.15  48.47]
True


### t4.py

In [12]:
import numpy as np

v1 = np.random.rand(3)
v2 = np.random.rand(3)

unit_v1 = v1 / np.linalg.norm(v1)
unit_v2 = v2 / np.linalg.norm(v2)

print("Unit Vector 1:\n", np.round(unit_v1, 2))
print("\nUnit Vector 2:\n", np.round(unit_v2, 2))

dot_product = np.dot(unit_v1, unit_v2)

print("\nDot Product:", np.round(dot_product, 2))

Unit Vector 1:
 [0.86 0.48 0.17]

Unit Vector 2:
 [0.71 0.07 0.7 ]

Dot Product: 0.77


## task-4

### t1.py

In [13]:
import numpy as np

arr = np.random.randint(1, 100, 20)

print("Array:\n", arr)

sorted_idx = np.argsort(arr)

smallest_idx = sorted_idx[:5]
largest_idx = sorted_idx[-5:]

print("\nIndices of 5 Smallest Values:\n", smallest_idx)
print("Values:\n", arr[smallest_idx])

print("\nIndices of 5 Largest Values:\n", largest_idx)
print("Values:\n", arr[largest_idx])

Array:
 [25 39 79 24 19 41 15 15 82 39 66 75 77 30 54 58 77 93 97 84]

Indices of 5 Smallest Values:
 [6 7 4 3 0]
Values:
 [15 15 19 24 25]

Indices of 5 Largest Values:
 [ 2  8 19 17 18]
Values:
 [79 82 84 93 97]


### t2.py

In [14]:
import numpy as np

arr = np.random.randint(1, 100, (5, 5))

print("Original Matrix:\n", arr)

row_sorted = np.sort(arr, axis=1)

final_matrix = np.sort(row_sorted, axis=0)

print("\nSorted Matrix:\n", final_matrix)

Original Matrix:
 [[96 66  2 24 35]
 [ 7 48 18  5 19]
 [70 56 66  9 22]
 [73 45 91 44 27]
 [53 38 85 59 80]]

Sorted Matrix:
 [[ 2  7 18 19 48]
 [ 5 22 35 66 70]
 [ 9 24 45 66 85]
 [27 44 56 73 91]
 [38 53 59 80 96]]


### t3.py

In [15]:
import numpy as np

A = np.random.randint(1, 21, 15)
B = np.random.randint(1, 21, 15)

print("Array A:\n", A)
print("\nArray B:\n", B)

common = np.intersect1d(A, B)
only_A = np.setdiff1d(A, B)
only_B = np.setdiff1d(B, A)

print("\nCommon Elements:\n", common)

print("\nElements Only in A:\n", only_A)

print("\nElements Only in B:\n", only_B)

Array A:
 [13  5  5  6 12  8 18 17 13 16  3 17 10 19  8]

Array B:
 [19  1 15  6 14  7 14 11  2  8 16  6 18  2 18]

Common Elements:
 [ 6  8 16 18 19]

Elements Only in A:
 [ 3  5 10 12 13 17]

Elements Only in B:
 [ 1  2  7 11 14 15]


## task-5

### t1.py

In [16]:
import numpy as np

arr = np.random.randint(1,100,10)

print("Original Array:\n", arr)

np.save("data.npy", arr)

np.savetxt("data.csv", arr, delimiter=",")

npy_data = np.load("data.npy")

csv_data = np.loadtxt("data.csv", delimiter=",")

print("\nLoaded from .npy:\n", npy_data)

print("\nLoaded from .csv:\n", csv_data)

print("\nAre both arrays equal?")
print(np.allclose(npy_data, csv_data))

Original Array:
 [75 44 82  8 35 82  2 43 27 89]

Loaded from .npy:
 [75 44 82  8 35 82  2 43 27 89]

Loaded from .csv:
 [75. 44. 82.  8. 35. 82.  2. 43. 27. 89.]

Are both arrays equal?
True


### t2.py

In [17]:
import numpy as np

marks = np.random.randint(0, 101, (50, 4))

np.savetxt("marks.csv", marks, delimiter=",")

data = np.loadtxt("marks.csv", delimiter=",")

total = np.sum(data, axis=1)

topper = np.argmax(total)

average = np.mean(data, axis=0)

below50 = np.where(data < 50)[0]

print("Marks:\n", data)

print("\nTopper Index:", topper)

print("\nSubject-wise Average:\n", average)

print("\nStudents Below 50 in Any Subject:\n", np.unique(below50))

Marks:
 [[ 5. 29.  4. 88.]
 [36. 54. 98. 80.]
 [ 2. 49. 75. 69.]
 [56. 70. 13. 52.]
 [ 0. 42.  1. 21.]
 [33. 41. 36. 21.]
 [81. 34.  8. 39.]
 [22.  7. 22. 97.]
 [70.  5. 93. 34.]
 [66. 40. 95. 48.]
 [60.  1. 40. 87.]
 [ 1. 30. 61. 85.]
 [77.  8. 76. 15.]
 [ 0. 83. 12. 32.]
 [70. 56. 13. 94.]
 [62. 37. 44. 31.]
 [70. 18. 10. 80.]
 [ 4. 22. 72. 99.]
 [58. 71. 96. 20.]
 [78. 13. 40. 69.]
 [35. 80. 95. 43.]
 [14. 59. 78. 81.]
 [22. 45. 13. 11.]
 [61. 37. 20. 34.]
 [44. 67. 19. 70.]
 [14. 75. 46. 19.]
 [34. 11. 98. 44.]
 [21. 55. 45. 31.]
 [18. 50. 21. 61.]
 [ 7. 17. 97. 59.]
 [41. 10. 24. 23.]
 [39. 93.  0. 32.]
 [ 4. 73. 98. 39.]
 [55. 33. 49. 45.]
 [78. 30.  0. 31.]
 [64. 42. 90. 23.]
 [80. 61. 45. 73.]
 [49. 41. 48. 99.]
 [51. 74. 73. 23.]
 [18. 65. 87. 84.]
 [74. 73. 55. 34.]
 [11. 55. 89. 88.]
 [87. 20. 36. 24.]
 [50. 23. 44. 22.]
 [28. 46.  7. 25.]
 [ 6.  6. 88. 81.]
 [84. 64. 69. 11.]
 [43. 44.  8. 95.]
 [79. 39. 66. 92.]
 [79. 17. 43. 57.]]

Topper Index: 48

Subject-wise Average:


## task-6

### t1.py

In [18]:
import numpy as np
import time

x = np.random.randint(1, 100, 1000000)

start = time.time()

result = []
for i in range(len(x)):
    result.append(x[i]**2 + 2*x[i] + 1)

end = time.time()

print("Loop Time:", end - start)

start = time.time()

result2 = x**2 + 2*x + 1

end = time.time()

print("Vectorized Time:", end - start)

print("\nSame Result?")
print(np.allclose(result, result2))

Loop Time: 0.46378469467163086
Vectorized Time: 0.009999990463256836

Same Result?
True


### t2.py

In [19]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

outer1 = np.einsum('i,j->ij', a, b)

outer2 = np.outer(a, b)

print("Using einsum:\n", outer1)

print("\nUsing outer:\n", outer2)

print("\nAre both equal?")
print(np.allclose(outer1, outer2))

Using einsum:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

Using outer:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

Are both equal?
True


### t3.py

In [20]:
import numpy as np
import time

a32 = np.random.rand(1000000).astype(np.float32)
a64 = np.random.rand(1000000).astype(np.float64)

print("Float32 Memory:", a32.nbytes, "bytes")
print("Float64 Memory:", a64.nbytes, "bytes")

start = time.time()
square32 = a32 ** 2
end = time.time()

print("\nFloat32 Squaring Time:", end - start)

start = time.time()
square64 = a64 ** 2
end = time.time()

print("Float64 Squaring Time:", end - start)

Float32 Memory: 4000000 bytes
Float64 Memory: 8000000 bytes

Float32 Squaring Time: 0.0020012855529785156
Float64 Squaring Time: 0.0049991607666015625


## main-task

### t1.py

In [21]:
import numpy as np

def stats_report(arr):
    arr = np.array(arr)

    shape = arr.shape
    minimum = np.min(arr)
    maximum = np.max(arr)
    mean = np.mean(arr)
    median = np.median(arr)
    std = np.std(arr)
    p25 = np.percentile(arr, 25)
    p75 = np.percentile(arr, 75)

    max_pos = np.unravel_index(np.argmax(arr), arr.shape)

    print("Shape :", shape)
    print("Minimum :", minimum)
    print("Maximum :", maximum)
    print("Mean :", mean)
    print("Median :", median)
    print("Standard Deviation :", std)
    print("25th Percentile :", p25)
    print("75th Percentile :", p75)
    print("Global Maximum Position (row, col) :", max_pos)

arr = np.array([
    [10, 25, 30],
    [45, 12, 18],
    [7, 60, 22]
])

stats_report(arr)

Shape : (3, 3)
Minimum : 7
Maximum : 60
Mean : 25.444444444444443
Median : 22.0
Standard Deviation : 16.412130412940243
25th Percentile : 12.0
75th Percentile : 30.0
Global Maximum Position (row, col) : (np.int64(2), np.int64(1))


### t2.py

In [22]:
import numpy as np

img = np.random.randint(0, 256, (100, 100), dtype=np.uint8)

horizontal_flip = np.fliplr(img)

vertical_flip = np.flipud(img)

center_crop = img[30:70, 30:70]

bright_img = np.clip(img + 20, 0, 255)

threshold_img = np.where(img > 128, 255, 0)

print("Original Shape:", img.shape)
print("Center Crop Shape:", center_crop.shape)
print("Threshold Image:\n", threshold_img)

Original Shape: (100, 100)
Center Crop Shape: (40, 40)
Threshold Image:
 [[255 255   0 ...   0 255 255]
 [  0   0 255 ...   0   0   0]
 [255 255   0 ... 255   0 255]
 ...
 [  0 255   0 ... 255   0 255]
 [  0   0 255 ...   0 255   0]
 [  0   0   0 ...   0 255 255]]


### t3.py

In [23]:
import numpy as np

marks = np.random.randint(35, 101, (30, 5))

avg_marks = np.mean(marks, axis=1)

ranks = avg_marks.argsort()[::-1].argsort() + 1

top_5 = np.argsort(avg_marks)[-5:][::-1]

bottom_5 = np.argsort(avg_marks)[:5]

correlation = np.corrcoef(marks[:, 0], marks[:, 1])

print("Marks:\n", marks)

print("\nAverage Marks Per Student:\n", avg_marks)

print("\nRanks:\n", ranks)

print("\nTop 5 Students Index:\n", top_5)

print("\nBottom 5 Students Index:\n", bottom_5)

print("\nCorrelation Between Subject 1 and Subject 2:\n", correlation)

Marks:
 [[ 81  78  43  39  38]
 [ 60  37  92  65  99]
 [ 98  70  54  49  55]
 [ 81  81  73  73  37]
 [ 46  37  50  75  96]
 [ 96  91  56  97  36]
 [ 44  95  63  94  69]
 [ 56  52  51  85  72]
 [ 82  87  38  90  51]
 [ 95  51  99  74  83]
 [ 86  88  92  43  51]
 [ 52  86  65  99  62]
 [ 44  89  97  46  37]
 [ 54  87  44  97  77]
 [ 64  82  64  35  53]
 [ 86  44  68  74  96]
 [ 99  47  76  61  69]
 [ 83  85  50  82  61]
 [ 82  58  87  60  50]
 [ 95  54  60  43  53]
 [ 70  68  66  87  45]
 [ 54  39 100  83  56]
 [ 90  46  97  70  43]
 [ 72  40  96  91  48]
 [ 48  69  61  57  65]
 [ 63  68  57  88  46]
 [ 94 100  62  71  87]
 [ 89  78  82  49  93]
 [ 52  85  55  83  41]
 [ 67  36  76  84  88]]

Average Marks Per Student:
 [55.8 70.6 65.2 69.  60.8 75.2 73.  63.2 69.6 80.4 72.  72.8 62.6 71.8
 59.6 73.6 70.4 72.2 67.4 61.  67.2 66.4 69.2 69.4 60.  64.4 82.8 78.2
 63.2 70.2]

Ranks:
 [30 11 21 17 27  4  6 24 14  2  9  7 25 10 29  5 12  8 18 26 19 20 16 15
 28 22  1  3 23 13]

Top 5 Students 

### t5.py

In [24]:
import numpy as np

returns = np.random.uniform(-0.1, 0.2, (12, 5))

mean_return = np.mean(returns, axis=0)

cov_matrix = np.cov(returns, rowvar=False)

weights = np.array([0.2] * 5)

portfolio_variance = weights @ cov_matrix @ weights

asset_risk = np.std(returns, axis=0)

highest_risk = np.argmax(asset_risk)

lowest_risk = np.argmin(asset_risk)

print("Monthly Returns:\n", returns)

print("\nMean Return Per Asset:\n", mean_return)

print("\nCovariance Matrix:\n", cov_matrix)

print("\nPortfolio Variance:\n", portfolio_variance)

print("\nHighest Risk Asset Index:", highest_risk)

print("Lowest Risk Asset Index:", lowest_risk)

Monthly Returns:
 [[ 0.07018604 -0.03075319  0.11273191  0.04735154  0.16126725]
 [ 0.11813758  0.09130196 -0.01811413  0.07319384  0.10249751]
 [-0.01349652  0.01988763  0.0932679   0.0023606  -0.07372854]
 [ 0.00242056  0.09934278  0.08826844  0.02121555  0.03051955]
 [ 0.11739902 -0.05741395 -0.06949335  0.03998804 -0.06155746]
 [ 0.16325489  0.08523914  0.19986672 -0.01931422  0.16375054]
 [ 0.0506105   0.14003681 -0.07104643 -0.0272137   0.13567809]
 [ 0.01176543 -0.00821917  0.19883199  0.10458007  0.16110252]
 [ 0.11156641 -0.0133384   0.01473976 -0.07971589  0.04322808]
 [-0.0753477   0.16954681  0.1669084  -0.05046302  0.01736792]
 [ 0.16463664 -0.08438442 -0.01253901  0.06003917  0.11114757]
 [ 0.11341475 -0.01602487  0.13293454  0.15257882  0.15173168]]

Mean Return Per Asset:
 [0.06954563 0.03293509 0.06969639 0.02705007 0.07858373]

Covariance Matrix:
 [[ 5.65985863e-03 -3.15394660e-03 -2.55843383e-03  1.17343856e-03
   2.38225625e-03]
 [-3.15394660e-03  6.64283314e-03  1.